name: Crear evento en Google Calendar

on:
  workflow_dispatch:
    inputs:
      title:
        description: "Título del evento"
        required: false
        default: "NO IR AL JUZGADO"
      start:
        description: "Inicio (RFC3339, ej. 2025-10-01T12:00:00+02:00)"
        required: true
      end:
        description: "Fin (RFC3339, ej. 2025-10-01T12:30:00+02:00)"
        required: true
      description:
        description: "Descripción"
        required: false
        default: "Creado desde GitHub Actions"

jobs:
  create-event:
    runs-on: ubuntu-latest
    steps:
      - name: Construir payload
        run: |
          cat > payload.json <<'JSON'
          {
            "secret":      "${{ secrets.WEBAPP_SECRET }}",
            "title":       "${{ github.event.inputs.title }}",
            "start":       "${{ github.event.inputs.start }}",
            "end":         "${{ github.event.inputs.end }}",
            "description": "${{ github.event.inputs.description }}"
          }
          JSON
          echo "Payload listo:"
          cat payload.json

      - name: Llamar al WebApp (POST con redirecciones)
        run: |
          set -e
          # -L sigue redirecciones (302 -> googleusercontent)
          # --fail-with-body hace que el job falle si HTTP>=400 pero imprima el cuerpo
          resp="$(curl -sS -L --fail-with-body \
            -X POST -H "Content-Type: application/json" \
            -d @payload.json "${{ secrets.WEBAPP_URL }}")"
          echo "$resp" | tee response.json

      - name: Validar respuesta
        run: |
          # Si no es JSON con ok=true, fallamos mostrando la respuesta
          if ! command -v jq >/dev/null; then sudo apt-get update -y && sudo apt-get install -y jq; fi
          ok=$(jq -r '.ok // empty' response.json || true)
          if [ "$ok" != "true" ] && [ "$ok" != "True" ]; then
            echo "Respuesta no OK:"
            cat response.json
            exit 1
          fi

      - name: Resumen
        run: |
          {
            echo "## ✅ Evento creado"
            echo
            echo '- **Título:**' "${{ github.event.inputs.title }}"
            echo '- **Inicio:**' "${{ github.event.inputs.start }}"
            echo '- **Fin:**'    "${{ github.event.inputs.end }}"
            echo
            echo "### Respuesta del WebApp"
            echo '```json'
            cat response.json
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"
