name: Crear evento en Google Calendar

on:
  workflow_dispatch:
    inputs:
      title:
        description: "Título del evento"
        required: false
        default: "NO IR AL JUZGADO"
      start:
        description: "Inicio (RFC3339, ej. 2025-10-01T12:00:00+02:00)"
        required: true
      end:
        description: "Fin (RFC3339, ej. 2025-10-01T12:30:00+02:00)"
        required: true
      description:
        description: "Descripción"
        required: false
        default: "Creado desde GitHub Actions"

jobs:
  create-event:
    runs-on: ubuntu-latest
    steps:
      - name: Check required secrets
        run: |
          test -n "${{ secrets.WEBAPP_URL }}"    || { echo "Falta secret WEBAPP_URL"; exit 1; }
          test -n "${{ secrets.WEBAPP_SECRET }}" || { echo "Falta secret WEBAPP_SECRET"; exit 1; }
          echo "Secrets OK"

      - name: Build payload
        run: |
          cat > payload.json <<'JSON'
          {
            "secret":      "${{ secrets.WEBAPP_SECRET }}",
            "title":       "${{ github.event.inputs.title }}",
            "start":       "${{ github.event.inputs.start }}",
            "end":         "${{ github.event.inputs.end }}",
            "description": "${{ github.event.inputs.description }}"
          }
          JSON
          echo "Payload:"
          cat payload.json

      - name: Call WebApp (POST with redirects kept as POST)
        run: |
          set -e
          resp="$(curl -sS -L --post301 --post302 --post303 --fail-with-body \
            -X POST -H "Content-Type: application/json" \
            -d @payload.json "${{ secrets.WEBAPP_URL }}")"
          echo "$resp" | tee response.json

      - name: Validate response (ok=true)
        run: |
          if ! command -v jq >/dev/null; then sudo apt-get update -y && sudo apt-get install -y jq; fi
          if ! jq empty response.json >/dev/null 2>&1; then
            echo "El cuerpo no es JSON:"
            cat response.json
            exit 1
          fi
          ok=$(jq -r '.ok // empty' response.json)
          if [ "$ok" != "true" ] && [ "$ok" != "True" ]; then
            echo "Respuesta no OK:"
            cat response.json
            exit 1
          fi

      - name: Summary
        run: |
          {
            echo "## ✅ Evento creado"
            echo
            echo "- **Título:** ${{ github.event.inputs.title }}"
            echo "- **Inicio:** ${{ github.event.inputs.start }}"
            echo "- **Fin:**    ${{ github.event.inputs.end }}"
            echo
            echo "### Respuesta del WebApp"
            echo '```json'
            cat response.json
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"
